server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/myproject?serverTimezone=Asia/Seoul
    username: root
    password: 1234
